import localFont from 'next/font/local'
import { Analytics } from '@vercel/analytics/next';

const gotham = localFont({
  src: [
    {path: '../../public/fonts/Gotham/Gotham Regular/Gotham Regular.otf', weight: '400'},
    {path: '../../public/fonts/Gotham/Gotham Medium/Gotham Medium.otf', weight: '200'},
    {path: '../../public/fonts/Gotham/Gotham Thin/Gotham Thin.otf', weight: '100'}
  ]
})

export const metadata = {
  title: 'Wrapped App 2023',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={gotham.className}>
        {children}
        <Analytics />
      </body>
    </html>
  )
}
